### PR TITLE
Go Application Structure

### PR DESCRIPTION
**Pull request by phillipahereza**
Man I tried moving things into packages and it beat me left right and center. So I decided to go with the [flat application structure](https://www.calhoun.io/flat-application-structure/)

Fixes #19

### CODE REVIEW

**Comment by AGMETEOR** [comment]
Auth and Token can be together? Thoughts?

**Comment by phillipahereza** [comment]
But t

> Auth and Token can be together? Thoughts?

But Token has stuff to do with saving the token to kvstore that isn't exactly auth.

**Comment by phillipahereza** [comment]
@AGMETEOR Also let's stop tracking `manifest.go` coz it seems it's autogenerated

**Comment by AGMETEOR** [comment]
> @AGMETEOR Also let's stop tracking `manifest.go` coz it seems it's autogenerated

I think it's need somewhere in the make process

**Pull request merged**
